version: '3'
services:
  mysql:
    image: mysql:8.0.18
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: techaway
      MYSQL_DATABASE: techaway
      MYSQL_ROOT_PASSWORD: techaway
    ports:
      - 3306:3306
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf4_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8001:80
    links:
      - mysql
volumes:
  persistent:
